### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by AndreLuna6** [SistemasTecTlaxiaco/infografia-AndreLuna6#2]
[Infografia_AndreEmmanuelLunaGonzalez.pdf](https://github.com/SistemasTecTlaxiaco/infografia-AndreLuna6/files/7118039/Infografia_AndreEmmanuelLunaGonzalez.pdf)

**Comment by JazminloRI** [comment]
Calificación final.  17

Jazmin Lopez Riveros

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
